### ISSUE TITLE
invalid conversion specification

### ISSUE THREAD

**Issue by jerkyrs** [mimoprotocol/mimo-automator#1]
What i did?
installed / setup ioctl 1.1.2 , imported account, setup endpoints, tested connectivity
cloned and ran source of mimoautoamter.bashrc.

ran following command
```
getTokenToIotxInputPrice io1kwtjyq0n4c4nsfn9egffh55dq4n43klz0u77n7 10000
```

Got an error
```printf: %065s: invalid conversion specification```

What i expected
to see price of iotx

Versions
bc 1.07.1
xargs (GNU findutils) 4.7.0

**Comment by j2-jonjohn** [comment]
Thanks for reporting this bug. Please try out the latest one with the fix: https://github.com/mimoprotocol/mimo-automator/commit/839782e3dad5f9981c9f576792987a544d713994

**Comment by jerkyrs** [comment]
works as expected, thanks
